### ISSUE TITLE
Sprite size is not correct

### ISSUE THREAD

**Issue by kat-liger** [jeherve/vk-sharing-jetpack#3]
The plugin is great, thank you very much for it!

But the VK sprite size is hardcoded as 16 x 16 px in size which is much smaller than other sprites in Jetpack Sharedaddy. As a result, it looks like this: 

![VK button as 16x16](https://img-fotki.yandex.ru/get/9755/49145008.1b/0_18b3b6_3813d740_orig)

I think it should look like this (helped me, at least):

    .sd-social-icon .sd-content ul li[class*='share-'].share-vkcom a.sd-button {
		background: #2B587A url('<?php echo plugins_url( 'vk-white.png', __FILE__ ); ?>') no-repeat;
		color: #fff !important;
		width: 33px;
		height: 32px;
		top: 12px;
	}

**Comment by jeherve** [comment]
Could you let me know your site URL, so I can take a look at how things look like on your site? I don't seem to be able to reproduce on my end.

**Comment by kat-liger** [comment]
Sure, you can take a look here: http://biggakniga.ru/2015/06/20/the-importance-of-being-loony/
I have changed file "class.vk-sharing-jetpack.php" back, to the default 16px width and height.

**Comment by jeherve** [comment]
I just released 1.2.2 to fix the issue. Thanks for the report!
